-- PostgreSQL 17. All monetary values are VND, with two decimal places.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ROLE_ADMIN', 'ROLE_STAFF')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id) ON DELETE RESTRICT,
    name VARCHAR(200) NOT NULL,
    short_code VARCHAR(30) NOT NULL UNIQUE CHECK (short_code ~ '^[A-Z][A-Z0-9_-]*$'),
    description TEXT,
    image_url VARCHAR(1000),
    cost_price NUMERIC(19,2) NOT NULL CHECK (cost_price >= 0),
    selling_price NUMERIC(19,2) NOT NULL CHECK (selling_price >= 0),
    stock_quantity INTEGER NOT NULL CHECK (stock_quantity >= 0),
    status VARCHAR(10) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX idx_products_category ON products(category_id);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    phone_number VARCHAR(20) UNIQUE,
    tiktok_id VARCHAR(100) UNIQUE,
    facebook_id VARCHAR(100) UNIQUE,
    address VARCHAR(1000),
    total_orders INTEGER NOT NULL DEFAULT 0 CHECK (total_orders >= 0),
    is_blacklisted BOOLEAN NOT NULL DEFAULT FALSE,
    notes TEXT,
    CHECK (phone_number IS NOT NULL OR tiktok_id IS NOT NULL OR facebook_id IS NOT NULL)
);
-- UNIQUE indexes also support phone/TikTok identity lookups and prevent duplicates.

CREATE TABLE live_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    tiktok_room_id VARCHAR(100),
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE,
    total_revenue NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (total_revenue >= 0),
    total_orders INTEGER NOT NULL DEFAULT 0 CHECK (total_orders >= 0),
    notes TEXT,
    CHECK (end_time IS NULL OR end_time >= start_time)
);
CREATE INDEX idx_live_sessions_room ON live_sessions(tiktok_room_id);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(50) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    live_session_id BIGINT REFERENCES live_sessions(id) ON DELETE RESTRICT,
    request_id UUID NOT NULL,
    channel VARCHAR(20) NOT NULL CHECK (channel IN ('TIKTOK', 'FACEBOOK', 'ZALO', 'PHONE')),
    subtotal_amount NUMERIC(19,2) NOT NULL CHECK (subtotal_amount >= 0),
    deposit_amount NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (deposit_amount >= 0),
    shipping_fee NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
    total_amount NUMERIC(19,2) NOT NULL CHECK (total_amount >= 0),
    paid_amount NUMERIC(19,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    remaining_amount NUMERIC(19,2) NOT NULL CHECK (remaining_amount >= 0),
    total_cost NUMERIC(19,2) NOT NULL CHECK (total_cost >= 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('DRAFT', 'CONFIRMED', 'SHIPPING', 'COMPLETED', 'CANCELLED')),
    payment_status VARCHAR(20) NOT NULL CHECK (payment_status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID')),
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('COD', 'BANK_TRANSFER')),
    proof_image_url VARCHAR(1000),
    tracking_code VARCHAR(100),
    comment_raw TEXT,
    stock_reserved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_order_user_request UNIQUE (user_id, request_id),
    CHECK (total_amount = subtotal_amount - deposit_amount + shipping_fee),
    CHECK (remaining_amount = total_amount - paid_amount),
    CHECK ((status = 'CANCELLED' AND NOT stock_reserved) OR (status <> 'CANCELLED' AND stock_reserved))
);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_status_created ON orders(status, created_at DESC);
CREATE INDEX idx_orders_live_session ON orders(live_session_id);
CREATE INDEX idx_orders_created ON orders(created_at DESC);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price_at_purchase NUMERIC(19,2) NOT NULL CHECK (price_at_purchase >= 0),
    cost_at_purchase NUMERIC(19,2) NOT NULL CHECK (cost_at_purchase >= 0),
    UNIQUE (order_id, product_id)
);
CREATE INDEX idx_order_items_product ON order_items(product_id);
